[project]
name = "analyser-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen-agentchat>=0.7.4",
    "autogen-core>=0.7.4",
    "autogen-ext[docker]>=0.7.4",
    "docker>=7.1.0",
    "dotenv>=0.9.9",
]
